### ISSUE TITLE
Error at model-training-notebook.ipynb when trying to predict from the endpoint

### ISSUE THREAD

**Issue by DanielRZapataS** [aws-samples/amazon-sagemaker-custom-recommender-system#2]
I got this error after running the pred = predictor.predict(input_vals) command. I'm using tensorflow 2.1 kernel.  

ModelError: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received client error (400) from primary with message "{ "error": "Matrix size-incompatible: In[0]: [1,610], In[1]: [9724,32]\n\t [[{{node StatefulPartitionedCall/StatefulPartitionedCall/model/dense_3/BiasAdd}}]]" }".

**Comment by TaihuaLi** [comment]
Hi Daniel - Thank you for reaching out and apologies on the delay. We've just addressed the issue in the master branch. Please let us know if any additional issue surfaces.
